name: Lint
on:
  - pull_request
jobs:
  lint:
    name: awesome-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install awesome-lint
        run: npm install -g awesome-lint
      - name: Run awesome-lint
        run: npx awesome-lint ./README.md

  link-check:
    runs-on: ubuntu-latest
    # check out the latest version of the code
    steps:
    - uses: actions/checkout@v4
    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
